{% set version = "6.0.0" %}
{% set sha256 = "6b8c4a833cf30230c0213d78dbac01af21387b298225de90ab56032ca79c0e0b" %}

package:
  name: lld
  version: {{ version }}

source:
  fn: lld-{{ version }}.src.tar.xz
  url: http://releases.llvm.org/{{ version }}/lld-{{ version }}.src.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and py<35]

requirements:
  build:
    - cmake >=3.4.3
    - ninja    # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - llvmdev =={{ version }}
    - libxml2
    - swig
    - libcxx   # [osx]
  run:
    - libcxx   # [osx]
    - llvmdev =={{ version }}
    - python

test:
  requires:
    - python {{ environ['PY_VER'] + '*' }}  # [win]
    - cmake >=3.4.3

  commands:
    - ld.lld --version  # [linux]
    - lld-link /?  # [win]

about:
  home: http://llvm.org/
  license: NCSA
  license_file: LICENSE.TXT
  summary: The LLVM Linker

extra:
  recipe-maintainers:
    - isuruf
